server:
  port: 8080

spring:
  cors:
    origin: "http://localhost:4200"
  datasource:
    url: jdbc:postgresql://localhost:5432/ttbay
    username: postgres
    password: postgres
  jpa:
    properties:
      show-sql: true
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    hibernate:
      ddl-auto: update


  server:
    error:
      include-message: true

jwt-set-url: https://www.googleapis.com/oauth2/v2/certs

