server:
  port: 8080

spring:
  cors:
    origin: ${FRONTEND_URL}
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    properties:
      show-sql: true
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    hibernate:
      ddl-auto: update


  server:
    error:
      include-message: true

jwt-set-url: https://www.googleapis.com/oauth2/v2/certs
awsaccesskey: ${AWS_ACCESS_KEY}
awssecretkey: ${AWS_SECRET_KEY}


