server:
  port: 8080

spring:
  cors:
    origin: "http://localhost:4200"
  datasource:
    url: jdbc:postgresql://ttbay-master-db.cbr56jv1s1rh.us-east-1.rds.amazonaws.com:5432/test
    username: ttbay
    password: team-ttbay
  jpa:
    properties:
      show-sql: true
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    hibernate:
      ddl-auto: update


  server:
    error:
      include-message: true

jwt-set-url: https://www.googleapis.com/oauth2/v2/certs

