server:
  port: ${PORT}

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ttbay
    username: postgres
    password: postgres
  jpa:
    properties:
      show-sql: true
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    hibernate:
      ddl-auto: create-drop
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}


  server:
    error:
      include-message: true

jwt-set-url: https://www.googleapis.com/oauth2/v2/certs

